### ISSUE TITLE
Add support for webkit's (Chrome/Firefox) up/down arrows for input type = number fields

### ISSUE THREAD

**Issue by yevheniyc** [xsanisty/jquery-calx#10]
I was wondering if you could add support for webkit's "up/down" arrows that are added to <input type = number..> fields. Here is a hack that I've implemented, which works fine but is very expensive: 

// here we are attaching calx to both keyup (when we are just going up/down with keyboard arrows), as well as webkit's "up/down" arrows on the <input type=number...> form fields

 $("input[type=number]").bind('keyup input', function(){
    // works fine, without visible latency
    $('#table_id').calx();
});

**Comment by ikhsan017** [comment]
Yes, I think I miss that, curently only field with [type= text] which is
listed, will add other type soon

Best regards,
Ikhsan

**Comment by yevheniyc** [comment]
Thank you so much!!!

**Comment by ikhsan017** [comment]
Hi @yevheniyc 

I just noticed that calx cover all input tag, and behave differently only on checkbox and radio , on other input, blur is the default event binding that trigger the calculation.

you can try to change it on calx init

```javascript
$('#id').calx({
    autoCalculateTrigger : 'keyup'
});
```

**Comment by yevheniyc** [comment]
Works great for the "keyup" event. It still has issues with webkit's "up/down" arrows on the type=number input fields. This will suffice for me, but the "up/down" arrows bug is still there!

**Comment by ikhsan017** [comment]
After searching for some reference, I think this link on SO is relevant to this issue

http://stackoverflow.com/questions/3940258/what-events-does-an-input-type-number-fire-when-its-value-is-changed

so, you can try to use the ```input``` or ```change``` event to trigger the calculation

```javascript
$('#id').calx({
    autoCalculateTrigger : 'keyup input'
});
```
