### ISSUE TITLE
2.2.0 too much recursion

### ISSUE THREAD

**Issue by sirNemanjapro** [xsanisty/jquery-calx#12]
When loaded in Firefox 37.0.1 the error is shown inside Firebug JavaScript console.
![2015-04-14_20-55-14](https://cloud.githubusercontent.com/assets/4259829/7144871/9a1221a8-e2e8-11e4-9bf0-07443fc23c6e.jpg)

**Comment by ikhsan017** [comment]
It usually caused by circular reference in formula, could you check it by enabling circular reference checker?

```javascript
$('#form').calx({
    checkCircularReference : true
});
```

**Comment by sirNemanjapro** [comment]
@ikhsan017 I'm checking it now.

**Comment by sirNemanjapro** [comment]
Circular reference detected, this may cause calx to stop working.
cell : A5
formula : A5=A1+A4

Please check each cells involved in the formula that has direct or indirect reference to A5

**Comment by sirNemanjapro** [comment]
@ikhsan017 I referenced cells A1, A2, A3, A4 inside a form, and A5, A6 outside the form. This is how the A5 looks like.

`<span data-cell="A5" data-formula="A5=A1+A4">N/A</span>`

**Comment by ikhsan017** [comment]
The way you define data-formula is wrong :), it should only contain the formula, the correct one should look like below

```html
<span data-cell="A5" data-formula="A1+A4">N/A</span>
```

**Comment by sirNemanjapro** [comment]
@ikhsan017 I could kiss you right now... Please write up some "idiot proof" documentation, for guys like me.

**Comment by ikhsan017** [comment]
It is already there in the doc I think
