### ISSUE TITLE
No donuts in chart sample :)

### ISSUE THREAD

**Issue by pax** [xsanisty/jquery-calx#17]
The provided sample doesn't for some reason render donut, pie and bar charts (see picture below) - like the [online example](http://prototype.xsanisty.com/calx2/chart.html) does. 

Also, in the online example source I can't see where the flot script (_jquery.flot.min.js_ or similar) is called. What am I missing?

![screen shot 2015-07-29 at 11 58 05](https://cloud.githubusercontent.com/assets/116795/8953711/3f2a0216-35e9-11e5-88f0-8bb0c2d71cd3.png)

Thanks

**Comment by ikhsan017** [comment]
@pax ,

I think you need to load required flot plugin for rendering the doughnut and pie

list of plugin can be found in flot site, or here https://github.com/xsanisty/jquery-calx/tree/master/js/flot_plugin

**Comment by ikhsan017** [comment]
on the online example, all required script was compacted to one js file :)

**Comment by ikhsan017** [comment]
I think I will close this issue as there is no real problem need to be resolved, kindly reopen the issue if you think this is still un-resolved
