### ISSUE TITLE
SUMIF is not working

### ISSUE THREAD

**Issue by AnthonyTerra** [xsanisty/jquery-calx#19]
I noticed SUMIF was always returning 0.  It seems the Range is being set to an object and not to an array causing the length property to error with an undefined error.

SUMIF : function(range, criteria) {
        var result = 0;
        for (var i = 0; i < range.length; i++) {
            result += (eval(range[i] + criteria)) ? range[i] : 0;
        }
        return result;
    },

should be

 SUMIF : function(rangeData, criteria) {
        var result = 0;
            var range = utility.objectToArray(rangeData);
            for (var i = 0; i < range.length; i++) {
                result += (eval(range[i] + criteria)) ? range[i] : 0;
            }
            return result;
    },

**Comment by ikhsan017** [comment]
Thanks for reporting,

currently sumif is already fixed, in progress fixing sumifs :)

**Comment by ikhsan017** [comment]
Just push the fix for ```SUMIF``` and ```SUMIFS```, please update to 2.2.6 and kindly test it :)

**Comment by AnthonyTerra** [comment]
Awesome, I will test and let you know.

**Comment by AnthonyTerra** [comment]
Sorry for the delay I was pulled off to another project

**Comment by AnthonyTerra** [comment]
Sorry for the delay I was pulled off to another project.  this issue is resolved
