### ISSUE TITLE
getter for formula-object

### ISSUE THREAD

**Issue by ecco8888** [xsanisty/jquery-calx#20]
Hello.

In order to access the internal formulas when registering custom formulas it would be nice to have access to the formula object by a getter function equivalent to getUtility().
I have localized the formulas to the german language by mapping the german formula names to the internal formulas. For this I have appended a getFormula() function. It would be nice, if this would be added to the main branch.

`  
getFormula : function () {
    return formula;
},
`

Regards
Tom

**Comment by ikhsan017** [comment]
Hi Tom,

thanks for the suggestion, its ow available on 2.2.7

Regards,
Ikhsan
