### ISSUE TITLE
Dynamic form

### ISSUE THREAD

**Issue by Mexiswow** [xsanisty/jquery-calx#23]
**2.2.7 version**
have a problem with dynamic_form

I entry **price** and **qty**
![joxi_screenshot_1458133367489](https://cloud.githubusercontent.com/assets/8334319/13813125/177e68ea-eb80-11e5-8197-c2d9b6c57663.png)

add new item
and entry price
have error in calculate. All numbers are 0
![joxi_screenshot_1458133386296](https://cloud.githubusercontent.com/assets/8334319/13813157/3f92bd90-eb80-11e5-9eff-3072d4022c32.png)

**2.2.6 version** and **2.2.5 version** it is working

**Comment by ikhsan017** [comment]
Thanks for reporting, will inspect this issue immediately

**Comment by ikhsan017** [comment]
Should be fixed in 2.2.8, closing for now
