### ISSUE TITLE
limitation to define data-cell 

### ISSUE THREAD

**Issue by ppbntl19** [xsanisty/jquery-calx#25]
is  there any limitation to define data-cell ?

I tried `Number_One ,NumberOne,Number,NUMBERONE `all these case are not working.
Only` NUMBERONE1 `is working.
Is this necessary to add a number with data-sell value ?

**Comment by ikhsan017** [comment]
Yes,
data-cell should use excel-like cell address like A1, B5, AB30, etc

regards,
Ikhsan
