### ISSUE TITLE
why the data-cell must be `[A-Z]+\d+` ? 

### ISSUE THREAD

**Issue by ystyle** [xsanisty/jquery-calx#28]
why the data-cell must be macth `[A-Z]+\d+` ?

how to confgure like taxMny1 reg: `[A-Za-z]+\d+` or `[A-Za-z]+\d+[A-Za-z]+`

 i found data-cell attr value only work such as `A1` `A2` `K3` `TEST1` , but no work like `money1` `tableName1_price`

**Comment by ikhsan017** [comment]
because at the first time, this plugin is intended to help me convert large excel based calculation into web form.
