### ISSUE TITLE
IF statement with string + formula? 

### ISSUE THREAD

**Issue by rayflores** [xsanisty/jquery-calx#44]
I am attempting to use the excel function '&' to add text to a formula:
in excel:  data-formula='IF(D8="ON","Alternative 3:  "&M76-1&"",IF(D8="AB","Alternative 3 "&M76-1&"","NA"))'
D8 = ON
MA76 = 10

result = #ERROR!

desired result:  Alternative 3:  9

how would I go about combining text + formula in calx?

**Comment by ikhsan017** [comment]
The & operator for concatenating string should work, maybe put M76-1 inside a bracket can do the trick, if not, you can use CONCAT() function
