### ISSUE TITLE
Implement COUNTIF(col, pattern)

### ISSUE THREAD

**Issue by ada10fl2** [xsanisty/jquery-calx#9]
Please implement the `COUNTIF` function

https://exceljet.net/formula/count-cells-that-contain-specific-text

#### Example

A B C
1 2 "asdasd"
3 2 "asddsa"
3 2 "dddddd"

```
=COUNTIF(A:A, 3)
=> 2

=COUNTIF(B:B, 2)
=> 3

=COUNTIF(C:C, "asd*")
=> 2
```

**Comment by ikhsan017** [comment]
Hi @ada10fl2 

Yeah, I think that would be great to implement this feature, unfortunately I am bad at regex, and the second parameters seem to be string pattern which require some knowledge .

But I will try to implement it.

regards
Ikhsan

**Comment by ikhsan017** [comment]
Hi @ada10fl2 

It seem there is a bug in countif and countifs, just push an update and bump the version to 2.0.5

regards
Ikhsan

**Comment by ada10fl2** [comment]
A easy fix would be to replace `*` with `.*`. Which is the Regex equivalent. 

Okey, I will try with that. Thanks!
